remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Mijn favoriete recepten
description: Een verzameling van hoofdzakelijk Nederlands-Spaanse en Spaans-Nederlandse recepten.
